In [2]:
import torch
torch.__version__

c:\Users\Mallinathan G\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


'1.12.1+cu116'

Tensors

Tensors are similar to lists/arrays but are often seen in multiple dimensions (greater than 3)
The biggest plus of tensors is data manipulation in bulk that has been optimised for efficiency like  running in GPUs

In [3]:
#defining a scalar (unit or 0 dim tensor)
scalar = torch.tensor(5)
scalar

tensor(5)

In [4]:
#to check the tensor dimension
scalar.ndim

0

In [5]:
#To get the value of the scalar
scalar.item()

5

In [6]:
#similar to vectors
vect = torch.tensor([77, 774])
print(vect)
print(vect.ndim)
print(vect.shape)

tensor([ 77, 774])
1
torch.Size([2])


In [7]:
#more complex
# Tensor
TENSOR = torch.tensor([[[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                        [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]], 
                        [[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])
4
torch.Size([1, 3, 3, 3])


Random init

In [8]:
random_Tensor = torch.rand(size=(1,3))
print(random_Tensor)
print(random_Tensor.dtype)

tensor([[0.5102, 0.5137, 0.3225]])
torch.float32


In [9]:
#Init with zeros or ones
zeros = torch.zeros(size = (3,4))
print(zeros)
ones = torch.ones(size = (3, 4))
print(ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Creating tenosr range

In [10]:
a_range_Tensor = torch.arange(start=0, end=20, step=2)
print(a_range_Tensor)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


To create a tensor A of shape tensor random_Tensor

In [11]:
Tensor_A = torch.zeros_like(input=random_Tensor)
print(Tensor_A)

tensor([[0., 0., 0.]])


DATATYPES
Torch.tensor have data types which can be classified into 3 main catagories

dtype=None (default-torch.float32, others include, torch.(float16 (half), float8)) -> For precision 

device=None (default cpu else torch.cuda)

requires_grad = False (/True) a feature to efficiently and automatically compute gradients during back prop

Please note that, when performing manipulations of 2 tensors, make sure dtype and device are same 

In [12]:
Tensor_cuda_16 = torch.tensor([3, 5, 54], dtype=torch.float16, device="cuda", requires_grad=False)
print(Tensor_cuda_16)

tensor([ 3.,  5., 54.], device='cuda:0', dtype=torch.float16)


To yield the attributes of a tensor (the one mentioned above)

In [13]:
#creating a random tensor
Tensor_rand = torch.rand(5,4)
print("The tensor is", Tensor_rand)
print("The type is: ", Tensor_rand.dtype)
print("The shape is ", Tensor_rand.shape)
print("The decice is ", Tensor_rand.device)

The tensor is tensor([[0.6693, 0.6998, 0.3987, 0.5417],
        [0.9219, 0.9644, 0.0999, 0.6125],
        [0.9594, 0.7954, 0.6628, 0.9068],
        [0.2373, 0.9488, 0.7798, 0.5734],
        [0.0129, 0.6953, 0.0325, 0.5756]])
The type is:  torch.float32
The shape is  torch.Size([5, 4])
The decice is  cpu


Tensor Operations

In [14]:
#create
sample_Tensor = torch.tensor([40, 50])
print(sample_Tensor+10)
print(sample_Tensor*2)
print(sample_Tensor-10)
print(torch.multiply(sample_Tensor, 10))
print(sample_Tensor/10)
sample_Tensor = sample_Tensor * 10
print(sample_Tensor)

tensor([50, 60])
tensor([ 80, 100])
tensor([30, 40])
tensor([400, 500])
tensor([4., 5.])
tensor([400, 500])


Matrix Multiplication

provided by torch.matmul() which is faster than manual (using loops)

In [15]:
sample_Tensor = torch.randint(low=0, high=30, size=(2,2))
print(sample_Tensor)
print(torch.matmul(sample_Tensor, sample_Tensor))
#In short
print(torch.mm(sample_Tensor, sample_Tensor))
# a depreciated method for the same
print(sample_Tensor @ sample_Tensor)
#Transpose
print("Transpose = ", sample_Tensor.T)

tensor([[ 3, 22],
        [ 1, 21]])
tensor([[ 31, 528],
        [ 24, 463]])
tensor([[ 31, 528],
        [ 24, 463]])
tensor([[ 31, 528],
        [ 24, 463]])
Transpose =  tensor([[ 3,  1],
        [22, 21]])


A sample torch neural network

In [16]:
#setting random seed for reproducibility
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=3, out_features=10)
x = Tensor_A
y = linear(x)
print(x, x.shape)
print(y, y.shape)

tensor([[0., 0., 0.]]) torch.Size([1, 3])
tensor([[ 0.5214, -0.4904,  0.4457,  0.0961, -0.1875,  0.3568,  0.0900,  0.4665,
          0.0631, -0.1821]], grad_fn=<AddmmBackward0>) torch.Size([1, 10])


Aggregate functions

In [17]:
torch.manual_seed(2)
#creating
sample_Tensor = torch.randint(low=0, high=35, size=(4,4))
print(sample_Tensor)
print(torch.max(sample_Tensor), torch.argmax(sample_Tensor))
print(torch.min(sample_Tensor), torch.argmin(sample_Tensor))
print(torch.sum(sample_Tensor))
mean = torch.mean(sample_Tensor.type(torch.half))
print(mean)
#To change mean from half (float16) to 64
mean = mean.type(torch.float64)
print(mean, mean.dtype)

tensor([[23, 17, 11,  9],
        [18, 14, 27,  5],
        [25, 11, 30, 31],
        [34, 25,  5,  8]])
tensor(34) tensor(12)
tensor(5) tensor(7)
tensor(293)
tensor(18.3125, dtype=torch.float16)
tensor(18.3125, dtype=torch.float64) torch.float64


Tensor shape manipulation

In [18]:
#creating
a = torch.arange(1,8)
print(a)
b = a.reshape(1, 7)
print(b)
c = a.view(1, 7)
print(c, a)
#view is like call by reference and altering c would alter a
c[:,0] = 23
print(c, a)
#stacking a 5 times to x
x = torch.stack([a, a, a, a, a], dim=0)
print(x)
x1 = torch.stack([a, a, a, a, a], dim=1)
print(x1)
#squeeze would remove all single dimensions 
print(c.squeeze())
#unsqueeze would do the opposite
print(a.unsqueeze(dim=1))
print(a.unsqueeze(dim=0))
#permute helps to change the dimensions the way i want
#note that permute returns a view and be careful with item manipulation
a = torch.rand(24, 124, 224, 3)
print(a.shape)
b = a.permute(3, 2, 0, 1)
print(b.shape)

tensor([1, 2, 3, 4, 5, 6, 7])
tensor([[1, 2, 3, 4, 5, 6, 7]])
tensor([[1, 2, 3, 4, 5, 6, 7]]) tensor([1, 2, 3, 4, 5, 6, 7])
tensor([[23,  2,  3,  4,  5,  6,  7]]) tensor([23,  2,  3,  4,  5,  6,  7])
tensor([[23,  2,  3,  4,  5,  6,  7],
        [23,  2,  3,  4,  5,  6,  7],
        [23,  2,  3,  4,  5,  6,  7],
        [23,  2,  3,  4,  5,  6,  7],
        [23,  2,  3,  4,  5,  6,  7]])
tensor([[23, 23, 23, 23, 23],
        [ 2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4],
        [ 5,  5,  5,  5,  5],
        [ 6,  6,  6,  6,  6],
        [ 7,  7,  7,  7,  7]])
tensor([23,  2,  3,  4,  5,  6,  7])
tensor([[23],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7]])
tensor([[23,  2,  3,  4,  5,  6,  7]])
torch.Size([24, 124, 224, 3])
torch.Size([3, 224, 24, 124])


Indexing is the same as list or numpy indexing
Numpy and pytorch
2 commands to convert between tensor and numpy

torch.from_numpy(numpy_array) -> numpy to tensor
Numpy works in float 64 by default and hence it will be float 64 unless typecasted

torch.tensor_variable.numpy() ->opposite
defaulting to float 32

In [19]:
import numpy as np
numpy_arr = np.arange(1.0, 10.0)
print(numpy_arr)
tensor_numpy = torch.from_numpy(numpy_arr)
print(tensor_numpy)
tensor = torch.arange(0, 10)
print(tensor)
numpy_tensor = tensor.numpy()
print(numpy_tensor)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
[0 1 2 3 4 5 6 7 8 9]


Reproducibility
Use random seed for the same
Make sure to set seed everytime during assignment

In [20]:
import random

#non reprodicible
tensor_A = torch.rand(3,4)
tensor_B = torch.rand(3,4)
print("A = ", tensor_A)
print("B = ", tensor_B)
print(tensor_A==tensor_B)

#with manual seed
torch.random.manual_seed(1)
tensor_C = torch.rand(3, 4)
torch.random.manual_seed(1)
tensor_D = torch.rand(3, 4)
print("C = ", tensor_C)
print("D = ", tensor_D)
print(tensor_C==tensor_D)

A =  tensor([[0.5007, 0.2445, 0.5864, 0.4192],
        [0.0114, 0.3972, 0.0118, 0.8016],
        [0.4381, 0.0169, 0.9721, 0.3844]])
B =  tensor([[0.8651, 0.7167, 0.7172, 0.3774],
        [0.4032, 0.1604, 0.4416, 0.2682],
        [0.7461, 0.0613, 0.6997, 0.7458]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
C =  tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])
D =  tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [21]:
#to get Nvidia info
!nvidia-smi

Mon Jun 19 17:18:57 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.98                 Driver Version: 535.98       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce MX150         WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P0              N/A / ERR! |    340MiB /  2048MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

Pytorch can work with GPUs better and has options to work on multiple GPUs

In [22]:
#assign gpu as device if available
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
#to know the number of GPUs available
print(torch.cuda.device_count())

cuda
1


In [23]:
#running on CPU
sample_Tensor = torch.arange(10)
print(sample_Tensor, sample_Tensor.device)

#shifting it to gpu
sample_Tensor_gpu = sample_Tensor.to(device)
print(sample_Tensor_gpu, sample_Tensor_gpu.device)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) cpu
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device='cuda:0') cuda:0


the cude:0 means that, the tenosr is stored in the 0th GPU and can be varied based on number of GPUs

Also know that numpy conversion wont work with GPU variables and hence need to be converted back 

sample_Tensor_gpu.numpy()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
d:\padipu\ML\pytorch_Course\fundamentals.ipynb Cell 39 in ()
----> 1 sample_Tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Hence,


In [24]:
numpy_tensor = sample_Tensor_gpu.cpu().numpy()
numpy_tensor

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)